name: Request ULF (make .alf)
on: workflow_dispatch
jobs:
  req:
    runs-on: ubuntu-latest
    steps:
      - uses: game-ci/unity-request-activation-file@v4
        with:
          unityVersion: 2022.3.22f1    # ← 프로젝트 버전과 정확히 일치시켜야 함
      - uses: actions/upload-artifact@v4
        with:
          name: unity-activation-file
          path: ./*.alf
